#配置服务器端口号
server:
  port: 8081
  ##配置spring
spring:
  application:
    name: SpringCloud-provider-dept
  datasource:
   username: root
   password: root
   url: jdbc:mysql://localhost:3306/sctd?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
   #配置连接池信息
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: org.gjt.mm.mysql.Driver
##配置mybatis
mybatis:
  type-aliases-package: com.wf.springcloud.bean
  mapper-locations: classpath:mapper/*.xml

#配置eureka的服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka8083.com:8083/eureka/,http://eureka8084.com:8084/eureka/,http://eureka8085.com:8085/eureka/
#改变eureka默认的描述信息
  instance:
    instance-id: springsloud-provider-dept-hystrix-8081
#显示访问地址的ip
    prefer-ip-address: true
#配置监控信息 软件名称，公司名称
info:
  app.name: wf.springcloud
  company.name: com.wf
